<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LocalNetChanger-Setup</AssemblyName>
    <RootNamespace>LocalNetChanger.Setup</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>..\..\LocalNetChanger\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="payload.zip" Condition="Exists('payload.zip')" />
    <EmbeddedResource Include="..\license.txt" Link="license.txt" />
  </ItemGroup>

</Project>
